import type { FishConfig } from '@reef/shared';

/**
 * Procedural sprite atlas.
 *
 * All artwork is generated by this file at runtime — no image assets, so the
 * game has zero third-party graphics and stays tiny over the wire. Each species
 * is baked once into an offscreen strip of tail-wiggle frames; drawing a fish is
 * then a single `drawImage`, which is what keeps 60 FPS realistic on a phone.
 */

export interface Palette {
  name: string;
  body0: string;
  body1: string;
  belly: string;
  fin: string;
  accent: string;
  eye: string;
  glow: string;
}

/** 13 original palettes referenced by `fish.palette` in the configuration. */
export const PALETTES: Palette[] = [
  { name: 'azure', body0: '#8fe9ff', body1: '#1f7ec2', belly: '#e8fbff', fin: '#0e5f9c', accent: '#37c6ff', eye: '#04212f', glow: 'rgba(70,200,255,0.55)' },
  { name: 'pearl', body0: '#f2fbff', body1: '#9fc4d8', belly: '#ffffff', fin: '#7ea8c0', accent: '#cfeeff', eye: '#173346', glow: 'rgba(210,240,255,0.5)' },
  { name: 'coral', body0: '#ffb49c', body1: '#e2593f', belly: '#ffe8dd', fin: '#b73f2c', accent: '#ff8a63', eye: '#3a1006', glow: 'rgba(255,140,100,0.5)' },
  { name: 'sunset', body0: '#ffd98a', body1: '#f07a2f', belly: '#fff2d2', fin: '#c9541c', accent: '#ffb347', eye: '#3d1a05', glow: 'rgba(255,180,90,0.5)' },
  { name: 'jade', body0: '#a8f5cf', body1: '#1f9e73', belly: '#e6fff4', fin: '#0f6b4e', accent: '#3ef2c0', eye: '#052a1e', glow: 'rgba(70,240,190,0.5)' },
  { name: 'steel', body0: '#d5e6f2', body1: '#5c7f99', belly: '#f4fbff', fin: '#3d5a70', accent: '#9dc3dd', eye: '#12222d', glow: 'rgba(160,200,230,0.45)' },
  { name: 'violet', body0: '#dcc9ff', body1: '#7a4fd8', belly: '#f3ecff', fin: '#4f2f9e', accent: '#a97bff', eye: '#1b0f38', glow: 'rgba(170,120,255,0.55)' },
  { name: 'lantern', body0: '#fff4c2', body1: '#c8a02a', belly: '#fffbe8', fin: '#8a6a12', accent: '#ffe273', eye: '#2b2205', glow: 'rgba(255,225,120,0.6)' },
  { name: 'gold', body0: '#fff0b0', body1: '#e0a106', belly: '#fffbe6', fin: '#a86f00', accent: '#ffd85e', eye: '#3a2600', glow: 'rgba(255,215,90,0.72)' },
  { name: 'jewel', body0: '#b6fff2', body1: '#0f9aa8', belly: '#e9fffc', fin: '#8a5a12', accent: '#3fe0d0', eye: '#04262b', glow: 'rgba(80,230,220,0.6)' },
  { name: 'neon', body0: '#c6ffe9', body1: '#12c8a0', belly: '#f0fff9', fin: '#0a7f66', accent: '#5cffe0', eye: '#052a22', glow: 'rgba(90,255,215,0.6)' },
  { name: 'ember', body0: '#ffd6c2', body1: '#d84a1e', belly: '#fff0e6', fin: '#8f2b0d', accent: '#ff7a3c', eye: '#33100a', glow: 'rgba(255,120,60,0.6)' },
  { name: 'abyss', body0: '#9db6ff', body1: '#2b2f7a', belly: '#dfe6ff', fin: '#171a4d', accent: '#6f7dff', eye: '#e9ecff', glow: 'rgba(120,130,255,0.6)' },
];

export function paletteFor(species: FishConfig | undefined): Palette {
  if (!species) return PALETTES[0]!;
  return PALETTES[((species.palette % PALETTES.length) + PALETTES.length) % PALETTES.length] ?? PALETTES[0]!;
}

export const SPRITE_FRAMES = 8;
/** Sprites are baked at this scale then drawn down: crisper than scaling up. */
const BAKE_SCALE = 2;

function roundedBody(ctx: CanvasRenderingContext2D, w: number, h: number, bulge: number, taper: number): void {
  // Symmetric fish body: nose at +X, tail at -X.
  ctx.beginPath();
  ctx.moveTo(w * 0.5, 0);
  ctx.bezierCurveTo(w * 0.34, -h * bulge, -w * 0.1, -h * 0.98, -w * (0.34 + taper), -h * 0.2);
  ctx.bezierCurveTo(-w * 0.2, h * 0.62, w * 0.16, h * 0.98, w * 0.5, 0);
  ctx.closePath();
}

function tail(ctx: CanvasRenderingContext2D, x: number, h: number, spread: number, curve: number): void {
  ctx.beginPath();
  ctx.moveTo(x, 0);
  ctx.quadraticCurveTo(x - h * 0.42, -h * spread * 0.2, x - h * spread, -h * spread);
  ctx.quadraticCurveTo(x - h * 0.24, 0, x - h * spread, h * spread);
  ctx.quadraticCurveTo(x - h * 0.42, h * spread * 0.2, x, 0);
  ctx.closePath();
  void curve;
}

/**
 * Bake a wiggle-strip for one species. Returns the canvas plus the frame width,
 * so the renderer can blit `frame = floor(phase) % SPRITE_FRAMES`.
 */
export function bakeFishSprite(species: FishConfig): { canvas: HTMLCanvasElement; frameWidth: number; frameHeight: number } {
  const size = Math.max(10, species.size);
  const boss = species.category === 'BOSS';
  const large = species.category === 'LARGE' || boss;
  const slender = species.special === 'speed';
  const round = species.special === 'bomb';
  const treasure = species.special === 'treasure';

  const bodyW = (round ? size * 2.0 : slender ? size * 3.0 : size * 2.35) * BAKE_SCALE;
  const bodyH = (round ? size * 1.85 : slender ? size * 0.9 : large ? size * 1.5 : size * 1.15) * BAKE_SCALE;
  const frameW = Math.ceil(bodyW * 1.42);
  const frameH = Math.ceil(bodyH * 2.5);
  const canvas = document.createElement('canvas');
  canvas.width = frameW * SPRITE_FRAMES;
  canvas.height = frameH;
  const ctx = canvas.getContext('2d')!;
  const pal = paletteFor(species);
  const cx = frameW / 2;
  const cy = frameH / 2;

  for (let f = 0; f < SPRITE_FRAMES; f += 1) {
    const phase = (f / SPRITE_FRAMES) * Math.PI * 2;
    const wig = Math.sin(phase);
    const wig2 = Math.cos(phase);
    ctx.save();
    ctx.translate(cx + f * frameW, cy);

    const glow = ctx.createRadialGradient(0, 0, bodyW * 0.1, 0, 0, bodyW * 0.78);
    glow.addColorStop(0, pal.glow);
    glow.addColorStop(1, 'rgba(0,0,0,0)');
    ctx.globalAlpha = 0.5;
    ctx.fillStyle = glow;
    ctx.beginPath();
    ctx.ellipse(0, 0, bodyW * 0.72, bodyH * 1.1, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.globalAlpha = 1;

    // ---- tail fin (behind body), rotates with the wiggle
    ctx.save();
    ctx.translate(-bodyW * (round ? 0.42 : 0.4), wig * bodyH * 0.06);
    ctx.rotate(wig * 0.34);
    ctx.fillStyle = pal.fin;
    ctx.strokeStyle = 'rgba(0,0,0,0.28)';
    ctx.lineWidth = Math.max(1, bodyW * 0.008);
    tail(ctx, 0, bodyH, round ? 0.92 : large ? 1.05 : 0.86, 0);
    ctx.fill();
    ctx.stroke();
    if (large || boss) {
      ctx.globalAlpha = 0.5;
      ctx.strokeStyle = pal.accent;
      ctx.lineWidth = Math.max(1, bodyW * 0.012);
      for (let i = -1; i <= 1; i += 1) {
        ctx.beginPath();
        ctx.moveTo(-bodyW * 0.04, 0);
        ctx.lineTo(-bodyH * (0.8 + i * 0.1), bodyH * i * 0.72);
        ctx.stroke();
      }
      ctx.globalAlpha = 1;
    }
    ctx.restore();

    // ---- dorsal + ventral fins
    ctx.fillStyle = pal.fin;
    ctx.beginPath();
    ctx.moveTo(-bodyW * 0.08, -bodyH * 0.82);
    ctx.quadraticCurveTo(bodyW * (0.06 + wig2 * 0.02), -bodyH * (boss ? 1.62 : 1.42), bodyW * 0.3, -bodyH * 0.6);
    ctx.closePath();
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(-bodyW * 0.14, bodyH * 0.78);
    ctx.quadraticCurveTo(-bodyW * 0.02, bodyH * (1.2 + wig * 0.08), bodyW * 0.16, bodyH * 0.6);
    ctx.closePath();
    ctx.fill();

    // ---- pectoral fin (front, animated)
    ctx.save();
    ctx.translate(bodyW * 0.1, bodyH * 0.32);
    ctx.rotate(0.5 + wig * 0.28);
    ctx.fillStyle = pal.fin;
    ctx.globalAlpha = 0.9;
    ctx.beginPath();
    ctx.ellipse(0, 0, bodyW * 0.17, bodyH * 0.3, -0.4, 0, Math.PI * 2);
    ctx.fill();
    ctx.globalAlpha = 1;
    ctx.restore();

    // ---- body
    const grad = ctx.createLinearGradient(0, -bodyH, 0, bodyH);
    grad.addColorStop(0, pal.body0);
    grad.addColorStop(0.52, pal.body1);
    grad.addColorStop(1, pal.belly);
    ctx.fillStyle = grad;
    ctx.strokeStyle = 'rgba(0,0,0,0.3)';
    ctx.lineWidth = Math.max(1, bodyW * 0.011);
    roundedBody(ctx, bodyW, bodyH, round ? 1.0 : 0.86, slender ? 0.1 : 0.02);
    ctx.fill();
    ctx.stroke();

    // ---- scales / stripes
    ctx.save();
    ctx.clip();
    ctx.globalAlpha = treasure ? 0.22 : 0.3;
    ctx.strokeStyle = pal.accent;
    ctx.lineWidth = Math.max(1, bodyW * 0.014);
    if (species.category === 'MEDIUM' || species.category === 'LARGE' || boss) {
      for (let i = -2; i <= 3; i += 1) {
        ctx.beginPath();
        ctx.moveTo(bodyW * (0.16 * i), -bodyH);
        ctx.quadraticCurveTo(bodyW * (0.16 * i + 0.06 * bodyW), 0, bodyW * (0.16 * i), bodyH);
        ctx.stroke();
      }
    } else {
      for (let r = 0; r < 4; r += 1) {
        for (let c = -3; c <= 2; c += 1) {
          ctx.beginPath();
          ctx.arc(bodyW * (0.1 * c), bodyH * (0.44 * r - 0.66), bodyW * 0.055, Math.PI, Math.PI * 2);
          ctx.stroke();
        }
      }
    }
    ctx.globalAlpha = 1;
    ctx.restore();

    // ---- species extras
    if (treasure) {
      // Treasure Coffer: a banded chest plate with a keyhole.
      ctx.fillStyle = 'rgba(90,60,10,0.85)';
      ctx.fillRect(-bodyW * 0.2, -bodyH * 0.5, bodyW * 0.62, bodyH * 1.0);
      ctx.fillStyle = '#ffd85e';
      ctx.fillRect(-bodyW * 0.2, -bodyH * 0.1, bodyW * 0.62, bodyH * 0.2);
      ctx.beginPath();
      ctx.arc(bodyW * 0.11, 0, bodyH * 0.16, 0, Math.PI * 2);
      ctx.fill();
      ctx.fillStyle = '#3a2a05';
      ctx.fillRect(bodyW * 0.09, -bodyH * 0.02, bodyH * 0.05, bodyH * 0.22);
    }
    if (round) {
      // Puffer Bomb: spikes + a lit fuse.
      ctx.fillStyle = pal.accent;
      for (let i = 0; i < 14; i += 1) {
        const a = (i / 14) * Math.PI * 2;
        const sx = Math.cos(a) * bodyW * 0.42;
        const sy = Math.sin(a) * bodyH * 0.9;
        ctx.beginPath();
        ctx.moveTo(sx, sy);
        ctx.lineTo(sx + Math.cos(a) * bodyW * 0.1, sy + Math.sin(a) * bodyH * 0.12);
        ctx.lineTo(sx + Math.cos(a + 0.35) * bodyW * 0.02, sy + Math.sin(a + 0.35) * bodyH * 0.03);
        ctx.closePath();
        ctx.fill();
      }
      ctx.strokeStyle = '#5a3b12';
      ctx.lineWidth = Math.max(1.5, bodyW * 0.02);
      ctx.beginPath();
      ctx.moveTo(0, -bodyH * 0.92);
      ctx.quadraticCurveTo(bodyW * 0.1, -bodyH * 1.3, bodyW * 0.02, -bodyH * 1.45);
      ctx.stroke();
      const spark = ctx.createRadialGradient(bodyW * 0.02, -bodyH * 1.48, 0, bodyW * 0.02, -bodyH * 1.48, bodyW * 0.1);
      spark.addColorStop(0, '#fffbe0');
      spark.addColorStop(0.5, '#ffb703');
      spark.addColorStop(1, 'rgba(255,120,0,0)');
      ctx.fillStyle = spark;
      ctx.beginPath();
      ctx.arc(bodyW * 0.02, -bodyH * 1.48, bodyW * 0.1, 0, Math.PI * 2);
      ctx.fill();
    }
    if (species.special === 'golden') {
      ctx.globalAlpha = 0.8;
      for (let i = 0; i < 7; i += 1) {
        const a = (i / 7) * Math.PI * 2 + phase * 0.4;
        ctx.fillStyle = 'rgba(255,255,220,0.85)';
        ctx.beginPath();
        ctx.arc(Math.cos(a) * bodyW * 0.3, Math.sin(a) * bodyH * 0.55, Math.max(1, bodyW * 0.014), 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.globalAlpha = 1;
    }
    if (boss) {
      // Leviathan: armour plates + bioluminescent nodes.
      ctx.fillStyle = 'rgba(255,255,255,0.14)';
      for (let i = 0; i < 4; i += 1) {
        ctx.beginPath();
        ctx.ellipse(bodyW * (0.22 - i * 0.14), -bodyH * 0.28, bodyW * 0.07, bodyH * 0.3, -0.3, 0, Math.PI * 2);
        ctx.fill();
      }
      for (let i = 0; i < 5; i += 1) {
        const gx = bodyW * (0.24 - i * 0.13);
        const gy = bodyH * (0.3 + Math.sin(phase + i) * 0.08);
        const gg = ctx.createRadialGradient(gx, gy, 0, gx, gy, bodyW * 0.06);
        gg.addColorStop(0, '#ffffff');
        gg.addColorStop(0.4, pal.accent);
        gg.addColorStop(1, 'rgba(0,0,0,0)');
        ctx.fillStyle = gg;
        ctx.beginPath();
        ctx.arc(gx, gy, bodyW * 0.06, 0, Math.PI * 2);
        ctx.fill();
      }
    }

    // ---- gill + belly shading
    ctx.strokeStyle = 'rgba(0,0,0,0.22)';
    ctx.lineWidth = Math.max(1, bodyW * 0.012);
    ctx.beginPath();
    ctx.moveTo(bodyW * 0.24, -bodyH * 0.5);
    ctx.quadraticCurveTo(bodyW * 0.16, 0, bodyW * 0.24, bodyH * 0.5);
    ctx.stroke();

    // ---- eye
    const eyeR = Math.max(2.4, bodyW * (boss ? 0.042 : round ? 0.055 : 0.05));
    const eyeX = bodyW * 0.32;
    const eyeY = -bodyH * (round ? 0.16 : 0.2);
    ctx.fillStyle = '#ffffff';
    ctx.beginPath();
    ctx.arc(eyeX, eyeY, eyeR * 1.5, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = pal.eye;
    ctx.beginPath();
    ctx.arc(eyeX + eyeR * 0.18, eyeY, eyeR, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = 'rgba(255,255,255,0.9)';
    ctx.beginPath();
    ctx.arc(eyeX - eyeR * 0.3, eyeY - eyeR * 0.42, eyeR * 0.42, 0, Math.PI * 2);
    ctx.fill();
    if (species.special === 'golden' || boss) {
      ctx.strokeStyle = pal.accent;
      ctx.lineWidth = Math.max(1, eyeR * 0.3);
      ctx.beginPath();
      ctx.arc(eyeX, eyeY, eyeR * 1.7, 0, Math.PI * 2);
      ctx.stroke();
    }

    // ---- mouth
    ctx.strokeStyle = 'rgba(0,0,0,0.4)';
    ctx.lineWidth = Math.max(1, bodyW * 0.012);
    ctx.beginPath();
    ctx.moveTo(bodyW * 0.48, bodyH * 0.06);
    ctx.quadraticCurveTo(bodyW * 0.4, bodyH * 0.2, bodyW * 0.3, bodyH * 0.18);
    ctx.stroke();

    ctx.restore();
  }

  return { canvas, frameWidth: frameW, frameHeight: frameH };
}

export interface SpriteCache {
  get(species: FishConfig | undefined): { canvas: HTMLCanvasElement; frameWidth: number; frameHeight: number } | undefined;
  frameWidthFor(species: FishConfig | undefined): number;
  clear(): void;
}

/** Memoises baked strips so each species costs one bake per page load. */
export function createSpriteCache(): SpriteCache {
  const cache = new Map<string, { canvas: HTMLCanvasElement; frameWidth: number; frameHeight: number }>();
  return {
    get(species) {
      if (!species) return undefined;
      let entry = cache.get(species.key);
      if (!entry) {
        entry = bakeFishSprite(species);
        cache.set(species.key, entry);
      }
      return entry;
    },
    frameWidthFor(species) {
      if (!species) return 64;
      return this.get(species)!.frameWidth;
    },
    clear() {
      cache.clear();
    },
  };
}

/* --------------------------------- cannon --------------------------------- */

/**
 * Player cannon. Drawn live (not baked) because it rotates smoothly and shows
 * recoil, charge glow and a level-dependent barrel count.
 */
export function drawCannon(
  ctx: CanvasRenderingContext2D,
  params: { x: number; y: number; angle: number; level: number; recoil: number; color: string; accent: string; local: boolean; aimAssist?: number },
): void {
  const { x, y, angle, level, recoil, color, accent, local } = params;
  const scale = 1 + (level - 1) * 0.11;
  ctx.save();
  ctx.translate(x, y);

  // Base shadow ring on the sea floor.
  ctx.globalAlpha = 0.5;
  ctx.fillStyle = 'rgba(0,0,0,0.45)';
  ctx.beginPath();
  ctx.ellipse(0, 26 * scale, 62 * scale, 15 * scale, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.globalAlpha = 1;

  // Pedestal.
  const ped = ctx.createLinearGradient(0, 44 * scale, 0, -6 * scale);
  ped.addColorStop(0, '#0a1f30');
  ped.addColorStop(0.55, '#1d4a68');
  ped.addColorStop(1, '#2f7ea6');
  ctx.fillStyle = ped;
  ctx.beginPath();
  ctx.moveTo(-52 * scale, 44 * scale);
  ctx.lineTo(-34 * scale, -6 * scale);
  ctx.lineTo(34 * scale, -6 * scale);
  ctx.lineTo(52 * scale, 44 * scale);
  ctx.closePath();
  ctx.fill();
  ctx.strokeStyle = 'rgba(140,220,255,0.5)';
  ctx.lineWidth = 2;
  ctx.stroke();

  // Rotating turret.
  ctx.rotate(angle + Math.PI / 2);
  const barrelLen = (44 + level * 9) * scale - recoil * 12;

  const steel = ctx.createLinearGradient(-16 * scale, 0, 16 * scale, 0);
  steel.addColorStop(0, '#12303f');
  steel.addColorStop(0.4, color);
  steel.addColorStop(0.62, '#eaf9ff');
  steel.addColorStop(1, '#12303f');

  const barrels = level >= 4 ? 2 : 1;
  for (let b = 0; b < barrels; b += 1) {
    const off = barrels === 1 ? 0 : (b === 0 ? -1 : 1) * 13 * scale;
    ctx.save();
    ctx.translate(off, 0);
    ctx.fillStyle = steel;
    ctx.beginPath();
    ctx.roundRect(-11 * scale, -barrelLen, 22 * scale, barrelLen, 7 * scale);
    ctx.fill();
    ctx.strokeStyle = 'rgba(4,20,30,0.85)';
    ctx.lineWidth = 2;
    ctx.stroke();
    // Muzzle ring + energy.
    ctx.fillStyle = accent;
    ctx.globalAlpha = 0.95;
    ctx.beginPath();
    ctx.ellipse(0, -barrelLen, 11 * scale, 4.4 * scale, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.globalAlpha = 1;
    if (recoil > 0.02) {
      const g = ctx.createRadialGradient(0, -barrelLen, 0, 0, -barrelLen, 44 * scale * (0.4 + recoil));
      g.addColorStop(0, 'rgba(255,255,255,0.85)');
      g.addColorStop(0.35, accent);
      g.addColorStop(1, 'rgba(0,0,0,0)');
      ctx.globalAlpha = recoil;
      ctx.fillStyle = g;
      ctx.beginPath();
      ctx.arc(0, -barrelLen, 44 * scale * (0.4 + recoil), 0, Math.PI * 2);
      ctx.fill();
      ctx.globalAlpha = 1;
    }
    ctx.restore();
  }

  // Turret housing.
  const housing = ctx.createRadialGradient(-6 * scale, 4 * scale, 4, 0, 0, 34 * scale);
  housing.addColorStop(0, '#dff6ff');
  housing.addColorStop(0.42, color);
  housing.addColorStop(1, '#0b2536');
  ctx.fillStyle = housing;
  ctx.beginPath();
  ctx.arc(0, 6 * scale, 27 * scale, 0, Math.PI * 2);
  ctx.fill();
  ctx.lineWidth = 2.5;
  ctx.strokeStyle = 'rgba(6,24,34,0.9)';
  ctx.stroke();

  // Power pips around the housing.
  for (let i = 0; i < level; i += 1) {
    const a = -Math.PI / 2 + (i - (level - 1) / 2) * 0.34;
    ctx.fillStyle = accent;
    ctx.beginPath();
    ctx.arc(Math.cos(a) * 20 * scale, 6 * scale + Math.sin(a) * 20 * scale, 3.1 * scale, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.restore();

  // Aim guide for the local player.
  if (local && params.aimAssist !== undefined) {
    ctx.save();
    ctx.globalAlpha = 0.28;
    ctx.strokeStyle = accent;
    ctx.lineWidth = 2;
    ctx.setLineDash([14, 20]);
    ctx.beginPath();
    ctx.moveTo(x + Math.cos(angle) * 58, y + Math.sin(angle) * 58);
    ctx.lineTo(x + Math.cos(angle) * (58 + params.aimAssist), y + Math.sin(angle) * (58 + params.aimAssist));
    ctx.stroke();
    ctx.restore();
  }
}

/* ------------------------------- projectiles ------------------------------- */

export function drawProjectile(ctx: CanvasRenderingContext2D, params: { x: number; y: number; angle: number; level: number; mine: boolean }): void {
  const { x, y, angle, level, mine } = params;
  const r = (7 + level * 1.9) * (mine ? 1 : 0.9);
  const hue = mine ? 186 : 30;
  ctx.save();
  ctx.translate(x, y);
  ctx.rotate(angle);

  // Compressible plasma core with a soft halo.
  const glow = ctx.createRadialGradient(0, 0, 0, 0, 0, r * 3.4);
  glow.addColorStop(0, 'rgba(255,255,255,0.95)');
  glow.addColorStop(0.32, `hsla(${hue},100%,66%,0.85)`);
  glow.addColorStop(1, `hsla(${hue},100%,50%,0)`);
  ctx.fillStyle = glow;
  ctx.beginPath();
  ctx.arc(0, 0, r * 3.4, 0, Math.PI * 2);
  ctx.fill();

  ctx.fillStyle = `hsl(${hue},100%,88%)`;
  ctx.beginPath();
  ctx.ellipse(0, 0, r * 1.5, r * 0.86, 0, 0, Math.PI * 2);
  ctx.fill();

  ctx.strokeStyle = `hsla(${hue},100%,70%,0.9)`;
  ctx.lineWidth = 1.8;
  ctx.beginPath();
  ctx.moveTo(-r * 1.5, 0);
  ctx.lineTo(-r * (3.4 + level * 0.6), 0);
  ctx.stroke();
  ctx.restore();
}
